spring:
  redis:
    database: 4
    host: 192.168.2.200
    port: 6379
    password: lh888

websocket:
  enable: true
  port: 8878

tcpsocket:
  enable: false # 暂时不开启
  port: 8879

#jwt:
#  accessToken:
#    secret: MIIBIjANBgkq  # 跟im-platfrom的secret必须一致