spring:
  redis:
    database: 3
    host: 192.168.0.172
    port: 6379
    password: xntd@app2022.

websocket:
  enable: true
  port: 8878

tcpsocket:
  enable: false # 暂时不开启
  port: 8879

#jwt:
#  accessToken:
#    secret: MIIBIjANBgkq  # 跟im-platfrom的secret必须一致