
#配置项目的数据源
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.200:3306/lh_pms_test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: d4ffd43cf462cab7

  redis:
    database: 5
    host: 192.168.2.200
    port: 6379
    password: lh888

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mapper
  mapper-locations:
    # *.xml的具体路径
    - classpath*:mapper/*.xml
#minio:
#  endpoint: http://127.0.0.1:9001 #内网地址
#  public: http://127.0.0.1:9001  #外网访问地址
#  accessKey: admin
#  secretKey: 12345678
#  bucketName: box-im
#  imagePath: image
#  filePath: file
#  videoPath: video

webrtc:
  iceServers:
    - urls: stun:stun.l.google.com:19302

#jwt:
#  accessToken:
#    expireIn: 1800 #半个小时
#    secret: MIIBIjANBgkq
#  refreshToken:
#    expireIn: 604800 #7天
#    secret: IKDiqVmn0VFU

logging:
  config: classpath:logback.xml

im:
  es:
    index:
      private: im_private_msg_test
      group: im_group_msg_test